###

GET http://localhost:3000/posts


###

GET http://localhost:3000/posts/6741d5392bd66898164c81a6


###

GET http://localhost:3000/posts?sender=Yuval


###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title":"therd post",
    "content": "This is my second post",
    "sender": "Yuval"
}


###
PUT http://localhost:3000/posts/6743422e65ed0e0906f1cd29
Content-Type: application/json

{
    "title": "Change post"
}


### Add a new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "676fec2dbfa4a384a54aac6b",
  "content": "This is a great post!",
  "author": "Yuval"
}

### Get all comments
GET http://localhost:3000/comments

### Get comments by post ID
GET http://localhost:3000/comments/63abcd1234abcd1234abcd12

### Update a comment
PUT http://localhost:3000/comments/63abcd5678abcd5678abcd56
Content-Type: application/json

{
  "content": "Updated comment content"
}

### Delete a comment
DELETE http://localhost:3000/comments/63abcd5678abcd5678abcd56


###

POST http://localhost:3000/users
Content-Type: application/json

{
    "userName":"Yuval",
    "email": "Yuval@gmail.com",
    "password": "123456",
    "refreshTokens" : ""
}



###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "userName": "yuvi",
    "email": "a@a.com",
    "password": "qwerty",
    "refreshTokens" : ""
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "userName": "yuvi",
    "email": "a@a.com",
    "password": "qwerty",
    "refreshTokens" : ""
}


###
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
    "userName": "yuvi",
    "email": "a@a.com",
    "password": "qwerty",
    "refreshTokens" : ""
}